using System.Collections.Generic;
public class stat_catRow
{
    public int id;
    public string name;
    public int type;
    public string attribute;
    public string members_slot;
    public int lv;
    public int evo;
    public int power;
    public int cooldown;
    public int weight;
    public int paymoney;
    public int hireexp;
    public int ownexp;
    public int exceedlimit;
    public string about;
    public string voice;
    public string illustra;
    public int weapon_on;
    public int addon_sideleft_on;
    public int addon_sideright_on;
    public int addon_back_on;
    public int attack_aniid;
    public int skill_id;
    public int skill_aniid;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class stat_cat : DatabaseSerializer
{
    private static stat_cat mInstance;
    public List<stat_catRow> rowList = new List<stat_catRow>();
    public static stat_cat GetInstance()
    {
        return mInstance ?? (mInstance = new stat_cat());
    }
    protected override void AddRow(object[] rowInfo)
    {
        stat_catRow row = new stat_catRow();
        row.id = GetInt(rowInfo[0]);
        row.name = GetString(rowInfo[1]);
        row.type = GetInt(rowInfo[2]);
        row.attribute = GetString(rowInfo[3]);
        row.members_slot = GetString(rowInfo[4]);
        row.lv = GetInt(rowInfo[5]);
        row.evo = GetInt(rowInfo[6]);
        row.power = GetInt(rowInfo[7]);
        row.cooldown = GetInt(rowInfo[8]);
        row.weight = GetInt(rowInfo[9]);
        row.paymoney = GetInt(rowInfo[10]);
        row.hireexp = GetInt(rowInfo[11]);
        row.ownexp = GetInt(rowInfo[12]);
        row.exceedlimit = GetInt(rowInfo[13]);
        row.about = GetString(rowInfo[14]);
        row.voice = GetString(rowInfo[15]);
        row.illustra = GetString(rowInfo[16]);
        row.weapon_on = GetInt(rowInfo[17]);
        row.addon_sideleft_on = GetInt(rowInfo[18]);
        row.addon_sideright_on = GetInt(rowInfo[19]);
        row.addon_back_on = GetInt(rowInfo[20]);
        row.attack_aniid = GetInt(rowInfo[21]);
        row.skill_id = GetInt(rowInfo[22]);
        row.skill_aniid = GetInt(rowInfo[23]);
        rowList.Add(row);
    }
}
